version: "3.3"
services:
  php-fpm:
    build:
      args:
        user: kevinkristian
        uid: 1000
      context: ./
      dockerfile: ./php/Dockerfile
    image: romannumerals-php-fpm
    container_name: romannumerals-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - romannumerals-network

  nginx:
    image: nginx:alpine
    container_name: romannumerals-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx/sites/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - romannumerals-network

  npm-ng-12: 
    build: ./npm
    container_name: romannumerals-node
    image: npm
    restart: unless-stopped
    tty: true
    volumes:
     - ../:/var/www 
    command: bash -c "npm i && ng s --host 0.0.0.0 --disableHostCheck"
    networks:
      - romannumerals-network

networks:
  romannumerals-network:
    driver: bridge