version: "3.8"

services:
  php-fpm:
    build:
      context: ./
      dockerfile: ./php/Dockerfile
      args:
        user: root
        uid: 1000
    image: php-fpm:8.0
    container_name: romannumerals-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - romannumerals-appnetwork

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx/sites/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - romannumerals-appnetwork
    depends_on:
      - php-fpm

  angular:
    build:
      context: ./
      dockerfile: ./npm/Dockerfile
    image: angular-cli:20
    container_name: romannumerals-app
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ../:/var/www
    command: bash -c "npm install && ng serve --host 0.0.0.0"
    networks:
      - romannumerals-appnetwork

networks:
  romannumerals-appnetwork:
    driver: bridge
